# Generated by Django 4.2.3 on 2023-07-10 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_alter_ad_advertiser_alter_click_click_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='view_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
