# Generated by Django 4.2.3 on 2023-07-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_remove_advertiser_clicks_remove_advertiser_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_set', to='advertiser_management.advertiser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_set', to='advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_set', to='advertiser_management.ad'),
        ),
    ]
